<template>
  <div id="game-container" class="game-container"></div>
</template>

<script setup>
import { onMounted, onUnmounted } from 'vue'
import { phaserStore } from '../store/phaserStore.js'
import { initGame, getRuntimeUrl } from '../phaser/initGame.js'

let game

onMounted(async () => {
  // Launch with the Spine 4.1 runtime by default. It will be replaced with
  // the appropriate version once a Spine JSON file is uploaded and parsed.
  game = await initGame(getRuntimeUrl('4.1'))
})

onUnmounted(() => {
  game?.destroy(true)
  phaserStore.setGameInstance(null)
})
</script>

<style lang="postcss" scoped>
.game-container {
  flex-grow: 1;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: #111318;
  border-radius: 16px;
  box-shadow: 0 8px 30px var(--color-shadow);
  min-width: 0;
  overflow: hidden;

  /* Use :deep to style the canvas generated by Phaser inside this component */
  :deep(canvas) {
    max-width: 100%;
    max-height: 100%;
    object-fit: contain;
    border-radius: 16px;
  }
}

/* Responsive styles for the game container */
@media (max-width: 1024px) {
  .game-container {
    width: 100%;
    min-height: 50vh;
  }
}
</style>
